name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install jsoncpp
      run: sudo apt-get install libjsoncpp-dev 

    - name: Build ./main
      run: make
